### ISSUE TITLE
请教几个驱动的问题

### ISSUE THREAD

**Issue by yuanwb1984** [Temperature6/OPi4_RTDevInfo#1]
B站上刷到的视频，手上没有OPi4，有OPi0+和nanopi neo2，都是H5的板子；
目前只有st7735的spi屏，i2c的屏还没到；
0、st7735能驱动，但是只会fbi显示个图片，ffplay播放视频，不知道怎么在fb0上显示系统信息；当作tty运行htop？
1、内核驱动有ssd130x-i2c.ko、ssd130x.ko、fb_ssd1306.ko，等屏到了再试试；
2、make了一下没报错也没生成可执行的文件。

**Comment by Temperature6** [comment]
这你问我没用啊，fb一直在尝试，从没有成功过，我也是Linux小白
